import esbuild from "esbuild";
import process from "process";
import fs from "node:fs";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Read wasm SQL adn save to inject later
const wasmBuffer = fs.readFileSync("node_modules/sql.js/dist/sql-wasm.wasm");
const wasmBase64 = wasmBuffer.toString("base64");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtinModules
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    define: {
        // Inject SQL WASM directly to plugin
        "INJECTED_WASM_BASE64": JSON.stringify(wasmBase64)
    },
    outfile: "main.js"
}).catch(() => process.exit(1));

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
